-- DropForeignKey
ALTER TABLE "Courses" DROP CONSTRAINT "Courses_streamId_fkey";

-- AlterTable
ALTER TABLE "Articles" ALTER COLUMN "banner_img" DROP NOT NULL,
ALTER COLUMN "banner_img" DROP DEFAULT,
ALTER COLUMN "img1" DROP NOT NULL,
ALTER COLUMN "img1" DROP DEFAULT,
ALTER COLUMN "img2" DROP NOT NULL,
ALTER COLUMN "img2" DROP DEFAULT,
ALTER COLUMN "slug" DROP NOT NULL;

-- AlterTable
ALTER TABLE "City" ALTER COLUMN "banner_img" DROP NOT NULL,
ALTER COLUMN "banner_img" DROP DEFAULT,
ALTER COLUMN "img1" DROP NOT NULL,
ALTER COLUMN "img1" DROP DEFAULT,
ALTER COLUMN "img2" DROP NOT NULL,
ALTER COLUMN "img2" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Colleges" ALTER COLUMN "logo_url" DROP NOT NULL,
ALTER COLUMN "bg_url" DROP NOT NULL,
ALTER COLUMN "rating" DROP NOT NULL,
ALTER COLUMN "intake_start_date" DROP NOT NULL;

-- AlterTable
ALTER TABLE "CollegesCourses" ALTER COLUMN "duration_in_months" DROP NOT NULL,
ALTER COLUMN "tution_fees" DROP NOT NULL,
ALTER COLUMN "hostel_fees" DROP NOT NULL,
ALTER COLUMN "one_time_fees" DROP NOT NULL,
ALTER COLUMN "other_fees" DROP NOT NULL;

-- AlterTable
ALTER TABLE "CollegewiseContent" ALTER COLUMN "banner_img" DROP NOT NULL,
ALTER COLUMN "img1" DROP NOT NULL,
ALTER COLUMN "img2" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Country" ALTER COLUMN "banner_img" DROP NOT NULL,
ALTER COLUMN "banner_img" DROP DEFAULT,
ALTER COLUMN "img1" DROP NOT NULL,
ALTER COLUMN "img1" DROP DEFAULT,
ALTER COLUMN "img2" DROP NOT NULL,
ALTER COLUMN "img2" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Courses" ALTER COLUMN "duration_in_months" DROP NOT NULL,
ALTER COLUMN "rating" DROP NOT NULL,
ALTER COLUMN "streamId" DROP NOT NULL,
ALTER COLUMN "banner_img" DROP NOT NULL,
ALTER COLUMN "img1" DROP NOT NULL,
ALTER COLUMN "img2" DROP NOT NULL;

-- AlterTable
ALTER TABLE "State" ALTER COLUMN "banner_img" DROP NOT NULL,
ALTER COLUMN "banner_img" DROP DEFAULT,
ALTER COLUMN "img1" DROP NOT NULL,
ALTER COLUMN "img1" DROP DEFAULT,
ALTER COLUMN "img2" DROP NOT NULL,
ALTER COLUMN "img2" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Stream" ALTER COLUMN "banner_img" DROP NOT NULL,
ALTER COLUMN "banner_img" DROP DEFAULT,
ALTER COLUMN "img1" DROP NOT NULL,
ALTER COLUMN "img1" DROP DEFAULT,
ALTER COLUMN "img2" DROP NOT NULL,
ALTER COLUMN "img2" DROP DEFAULT;

-- AddForeignKey
ALTER TABLE "Courses" ADD CONSTRAINT "Courses_streamId_fkey" FOREIGN KEY ("streamId") REFERENCES "Stream"("id") ON DELETE SET NULL ON UPDATE CASCADE;
